spring:
  main:
    banner-mode: off
logging:
  file:
    name: /var/log/iac.log
  pattern:
    file: "{\"time\": \"%d\"
          , \"level\": \"%p\"
          , \"pid\": \"${PID:- }\"
          , \"thread\": \"%t\"
          , \"app\": \"${spring.application.name}\"
          , \"source\": \"%logger{255}:%L\"
          , \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"
    console: "{\"time\": \"%d\"
                       , \"level\": \"%p\"
                       , \"pid\": \"${PID:- }\"
                       , \"thread\": \"%t\"
                       , \"app\": \"${spring.application.name}\"
                       , \"source\": \"%logger{255}:%L\"
                       , \"message\": \"%replace(%m%wEx{6}){'[\r\n]+', '\\n'}%nopex\"}%n"