apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac
spec:
  selector:
    matchLabels:
      run: iac
  replicas: 1
  template:
    metadata:
      labels:
        run: iac
    spec:
      containers:
        - name: iac
          image: 192.168.1.190:5000/iac
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "production"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: iac
  labels:
    run: iac
spec:
  ports:
    - port: 8080
      nodePort: 32767
  selector:
    run: iac
  type: NodePort
